services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: trade-hedge-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-trade_hedge}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - trade-hedge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Основное приложение Trade Hedge
  trade-hedge:
    image: ${TRADE_HEDGE_IMAGE:-your-registry.com/trade-hedge:latest}
    container_name: trade-hedge-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - trade-hedge-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
    driver: local
networks:
  trade-hedge-network:
    driver: bridge

